### PR TITLE
Webpack2

### PR DESCRIPTION
**Pull request by ryankurte**

### CODE REVIEW

**Comment by peabnuts123** [comment]
Oh, do you need help with Webpack. I know webpack things. One day I will put aside some time for this repo

**Comment by peabnuts123** [comment]
Oh sweet this branch is already deleted anyway.

**Comment by ryankurte** [comment]
I think I need help with all the things :-P

Updated to webpack 2, because in the time I have been working on this the frontend stuff has got out of date three times. Merged to master and using create-react-app now for minimal complexity for as long as possible.

**Comment by peabnuts123** [comment]
Yeah Webpack 2 is what you want. I'ma try to put some time aside this week to check out this repo at least

**Pull request merged**
